### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nils-se** [jcasoft/GoogleCalendar-Skill#5]
The skill doesn't work with the new version of mycroft. Mycroft doesnt look for skills in /opt/mycroft/third_party

I put the skill in ~/mycroft-core/mycroft/skills/
saved the config like described in the readme with the following content:

>  [GoogleCalendarSkill]
>     loginEnabled = False
>     calendar_id = 'mygmailadress@gmail.com' # For add events to your calendar
>     maxResults = 10
>     gmt = '-02:00'
>     timeZone = 'Europe/Berlin'
>     attendees_own = ''
>     attendees_family = ''
>     attendees_work = ''
>     reminders_email = 1440  # in minutes --> 24 *60
>     reminders_popup = 10    # in minutes
>     default_duration = 1    # Default duration of appointments, in hours
>     time_format = 24h   # Options are 12h and 24h

But "./start.sh skills" fails to load the skill.

`2016-12-28 01:00:30,051 - mycroft.skills.core - ERROR - Failed to load skill: mycroft-googlecalendar-skill
Traceback (most recent call last):
  File "/home/nils/mycroft-core/mycroft/skills/core.py", line 101, in load_skill
    skill = skill_module.create_skill()
  File "/home/nils/mycroft-core/mycroft/skills/mycroft-googlecalendar-skill/__init__.py", line 1191, in create_skill
    return GoogleCalendarSkill()
  File "/home/nils/mycroft-core/mycroft/skills/mycroft-googlecalendar-skill/__init__.py", line 279, in __init__
    self.loginEnabled = self.config.get('loginEnabled')
AttributeError: 'NoneType' object has no attribute 'get'
`

**Comment by nils-se** [comment]
Config has to be integrated in mycroft.conf:
``` 
"GoogleCalendarSkill": {
    "loginEnabled": false,
    "calendar_id": "MAILADRESS@gmail.com",
    "maxResults": 4,
    "gmt": "+01:00",
    "timeZone": "Europe/Berlin",
    "attendees_own": "",
    "attendees_family": "",
    "attendees_work": "",
    "reminders_email": 1440,
    "reminders_popup": 10,
    "default_duration": 1,
    "time_format": "24h"
  },
```

And the skill has to be saved under mycroft-core/mycroft/skills and in __init__.py it has to be
`third_party_skill 	= "/home/nils/dev/mycroft/skills/GoogleCalendar-Skill"`

**Comment by nils-se** [comment]
It's a problem with whole day events. Google gives back the date format in y-m-d and skill expects date and time.
